sudo: false # The explicit sudo: false will let it build in Docker (for speed) even if you have a pre-docker repo, according to Travis support

language: cpp

os:
  - linux
#  - osx

compiler:
  - gcc
#  - clang

before_install:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=XTketTK9zlvjDRh6QUHSH2Mb2u1hba2BD

#install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y -qq lcov curl

# move on from standard crusty travis default compiler
# http://stackoverflow.com/a/30925448/276193
# http://stackoverflow.com/a/33203355/276193
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
#    - gcc-4.8
    - g++-4.8
#    - clang
    - gcov-4.6
    - cmake

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - cmake --build . --target coveralls
  - cat coveralls.json
  - test/all_tests

notifications:
  email: false

after_success:
#  - coveralls --root .. -E ".*extern.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
#  - coveralls --root .. --exclude extern --exclude CMakeFiles --exclude test --gcov-options '\-lp'
  - bash <(curl -s https://codecov.io/bash -ssrc) #http://stackoverflow.com/questions/13116488/detailed-guide-on-using-gcov-with-cmake-cdash