sudo: false # The explicit sudo: false will let it build in Docker (for speed) even if you have a pre-docker repo, according to Travis support

language: cpp

os:
  - linux
#  - osx

compiler:
#  - gcc #gcc with C++11 (4.8+) support gives me some mismatched gcov version errors for coverage
  - clang

before_install:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=XTketTK9zlvjDRh6QUHSH2Mb2u1hba2BD



# move on from standard crusty travis default compiler
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
#    - gcc-5
    - g++-5
    - clang
    - cmake

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - cmake --build . --target coveralls
  - cat coveralls.json
  - test/all_tests

notifications:
  email: false

after_success:
#  - bash <(curl -s https://codecov.io/bash -gsrc) #http://stackoverflow.com/questions/13116488/detailed-guide-on-using-gcov-with-cmake-cdash
#  - curl -s https://codecov.io/bash >> codecov
#  - chmod +x codecov
#  - ./codecov -gtest/*
  - cd build
  - bash <(curl -s https://codecov.io/bash) -psrc
