language: cpp

#install:
#  - sudo pip install cpp-coveralls

#dist: trusty

os:
  - linux
#  - osx

#before_install:
#- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
#         echo "On LINUX from .travis.yml"
#      && echo "Penguins!"
#      ;
#    else
#         echo "Not on LINUX from .travis.yml"
#      && echo "Can do brew and stuff!"
#      ;
#    fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - test/all_tests

#after_success:
#  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false