language:
  - cpp

#install:
#  - sudo pip install cpp-coveralls

before_install:
 - sudo apt-get -y upgrade cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./all_tests

#after_success:
#  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false