language: cpp

#install:
#  - sudo pip install cpp-coveralls

#dist: trusty

os:
  - linux
#  - osx

before_install:
  - bash <(if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
           echo "On LINUX from .travis.yml"
        && echo "Penguins!"
        ;
      else
           echo "Not on LINUX from .travis.yml"
        && echo "Can do brew and stuff!"
        ;
      fi)
  - pip install cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - test/all_tests

#after_success:
#  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
  - bash <(curl -s https://codecov.io/bash)