# good dmeo here . . .
# https://github.com/SwissTPH/openmalaria/blob/master/appveyor.yml

install:
  - git submodule init && git submodule update


build_script:
  - echo %CD%
  - mkdir build
  - echo %CD%
  - ps: cd build
  - echo %CD%
  - cmake ..
  - cmake --build

test_script:
  - echo %CD%
  - ps: cd build
  - echo %CD%
  - ctest
  - echo %CD%