# good dmeo here . . .
# https://github.com/SwissTPH/openmalaria/blob/master/appveyor.yml

install:
  - git submodule init && git submodule update

build_script:
  - mkdir build
  - ps: cd build
  - cmake ..
  - cmake --build .

test_script:
  - ps: cd test
  - dir
  - ps: cd Debug
  - dir
  - all_tests
