build_script:
  - echo %CD%
  - mkdir build
  - echo %CD%
  - ps: cd build
  - echo %CD%
  - cmake ..
  - cmake --build

test_script:
  - echo %CD%
  - ps: cd build
  - echo %CD%
  - ctest
  - echo %CD%